# Generated by Django 4.1.5 on 2023-03-22 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Scan', models.BooleanField(default=False)),
                ('points_50', models.BooleanField(default=False)),
                ('points_250', models.BooleanField(default=False)),
                ('points_500', models.BooleanField(default=False)),
                ('max_Score', models.BooleanField(default=False)),
                ('All_cat', models.BooleanField(default=False)),
                ('Top_10', models.BooleanField(default=False)),
                ('Top_5', models.BooleanField(default=False)),
                ('Top_3', models.BooleanField(default=False)),
                ('Top_1', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_Added', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('score', models.IntegerField(default=0)),
                ('userRank', models.IntegerField(default=0)),
                ('Drink', models.IntegerField(default=0)),
                ('Snack', models.IntegerField(default=0)),
                ('Vegetable', models.IntegerField(default=0)),
                ('Protein', models.IntegerField(default=0)),
                ('Fruit', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
        migrations.AddField(
            model_name='history',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='achievements',
            name='Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
