# Generated by Django 4.1.5 on 2023-03-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_achievements_history_profile_delete_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
