# Generated by Django 4.1.5 on 2023-03-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
