# Generated by Django 4.1.5 on 2023-03-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_history_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='image',
        ),
    ]
