# Generated by Django 4.1.5 on 2023-03-01 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_history_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_Added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
