# Generated by Django 4.1.5 on 2023-03-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_rank_profile_userrank'),
        ('users', '0012_history_date_added'),
    ]

    operations = [
    ]
