# Generated by Django 4.1.5 on 2023-03-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20230302_1131'),
        ('users', '0013_merge_20230302_1132'),
    ]

    operations = [
    ]
