# Generated by Django 4.1.5 on 2023-03-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20230302_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Scan', models.BooleanField(default=False)),
                ('points_50', models.BooleanField(default=False)),
                ('points_250', models.BooleanField(default=False)),
                ('points_500', models.BooleanField(default=False)),
                ('max_Score', models.BooleanField(default=False)),
                ('All_cat', models.BooleanField(default=False)),
                ('Top_10', models.BooleanField(default=False)),
                ('Top_5', models.BooleanField(default=False)),
                ('Top_3', models.BooleanField(default=False)),
                ('Top_1', models.BooleanField(default=False)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
