# Generated by Django 4.1.5 on 2023-03-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_achievements'),
        ('users', '0015_profile_drink_profile_fruit_profile_protein_and_more'),
    ]

    operations = [
    ]
