# Generated by Django 4.1.5 on 2023-03-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_history_score'),
        ('users', '0016_merge_20230322_1832'),
    ]

    operations = [
    ]
