# Generated by Django 4.1.7 on 2023-02-24 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Scanner', '0004_demo_rank_delete_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='rank',
            field=models.IntegerField(default=9999, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rank'),
        ),
    ]
