# Generated by Django 4.1.5 on 2023-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=15)),
                ('userScore', models.CharField(max_length=99999)),
                ('userEmail', models.CharField(max_length=32)),
                ('userPw', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=32)),
            ],
        ),
    ]
