# Generated by Django 4.1.5 on 2023-02-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='userID',
        ),
    ]
