# Generated by Django 4.1.7 on 2023-02-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Scanner', '0002_score_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'verbose_name': 'Score List', 'verbose_name_plural': 'Score List'},
        ),
        migrations.AlterField(
            model_name='demo',
            name='userScore',
            field=models.CharField(default=0, max_length=99999),
        ),
        migrations.AlterField(
            model_name='rank',
            name='c_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Food_Scanner.demo'),
        ),
    ]
