# Generated by Django 4.1.5 on 2023-02-28 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Scanner', '0006_remove_score_client_score_player_score_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('c_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Food_Scanner.demo')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='rank')),
            ],
        ),
        migrations.AlterModelOptions(
            name='demo',
            options={'verbose_name': 'Player List', 'verbose_name_plural': 'Player List'},
        ),
        migrations.RemoveField(
            model_name='demo',
            name='rank',
        ),
    ]
