# Generated by Django 4.1.5 on 2023-03-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Scanner', '0007_rank_alter_demo_options_remove_demo_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='barcodes_scanned')),
            ],
        ),
    ]
