# Generated by Django 4.1.5 on 2023-03-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Scanner', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
